name: Funktionswunsch
description: Eine Verbesserung vorschlagen
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Welches Problem soll gelöst werden?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Gewünschte Lösung
    validations:
      required: true
