const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('app/static/collection-shelf.js','utf8');
let click,focused=false,tick,toggleClick,hover=false,reduced={matches:false};
const empty={addEventListener(name,handler){assert.equal(name,'click');click=handler;}};
const field={focus(options){assert.equal(options.preventScroll,true);focused=true;}};
const toggle={addEventListener(name,handler){toggleClick=handler;},setAttribute(name,value){this[name]=value;}};
const media=Array.from({length:7},()=>({title:'',style:{setProperty(name,value){this[name]=value;}},label:{textContent:''},brand:{textContent:''},side:{replaceChildren(){},appendChild(){}},querySelector(selector){return selector==='.regal-spine-title'?this.label:selector==='.regal-case-brand'?this.brand:this.side;},setAttribute(name,value){this[name]=value;},removeAttribute(name){delete this[name];}}));
const wrap={dataset:{shelfCases:JSON.stringify(Array.from({length:10},(_,i)=>({title:'Title '+i,style:i%2?'bluray':'dvd',href:'/collector/item/'+i,format:'DVD',cover:''})))},querySelectorAll(selector){assert.equal(selector,'.regal-item');return media;},closest(){return {matches(){return hover;}};}};
const doc={hidden:false,querySelector(selector){return selector==='.dashboard-add-category'?empty:selector==='.regal-rotation-toggle'?toggle:selector.includes('input[name=')?field:null;},querySelectorAll(){return [wrap];}};
vm.runInNewContext(source,{document:doc,window:{requestAnimationFrame(fn){fn();},matchMedia(){return reduced;},setInterval(fn,ms){assert.equal(ms,12000);tick=fn;}}});
click();assert.equal(focused,true);tick();assert.equal(media[0].label.textContent,'Title 1');assert.equal(media[0].className,'regal-media regal-item case-bluray');
assert.equal(media[0].href,'/collector/item/1');assert.equal(media[0]['aria-label'],'Title 1 öffnen');
hover=true;tick();assert.equal(media[0].label.textContent,'Title 1');hover=false;
toggleClick();tick();assert.equal(media[0].label.textContent,'Title 1');assert.equal(toggle['aria-pressed'],'true');
toggleClick();doc.hidden=true;tick();assert.equal(media[0].label.textContent,'Title 1');doc.hidden=false;
reduced.matches=true;tick();assert.equal(media[0].label.textContent,'Title 1');reduced.matches=false;
tick();assert.equal(media[0].label.textContent,'Title 2');assert.equal(media[3].className,'regal-media regal-item case-bluray regal-pull-default');
wrap.dataset.shelfCases=JSON.stringify(Array.from({length:10},(_,i)=>({title:'Sorted '+i,style:'dvd',height:250-i*10,href:'/item/'+i,cover:''})));
vm.runInNewContext(source,{document:doc,window:{requestAnimationFrame(fn){fn();},matchMedia(){return reduced;},setInterval(fn){tick=fn;}}});
tick();assert.equal(media[0].label.textContent,'Sorted 7');assert.equal(media[0].href,'/item/7');
assert.equal(media[0].style['--case-height'],'180px');
assert.equal(media[6].label.textContent,'Sorted 1');
vm.runInNewContext(source,{document:{querySelector(){return null;},querySelectorAll(){return [];}},window:{matchMedia(){return reduced;},setInterval(){}}});
console.log('OK: native category focus, automatic titles/formats, pause/resume, hover, hidden tab, reduced motion, missing editor controls');
let shakeClick,shakeTick;const timers=[],classes=new Set(),knob={disabled:false,addEventListener(_,fn){shakeClick=fn;}},status={textContent:''};
const original={href:'/collector/item/99',style:{setProperty(){}}};
const cabinet={querySelectorAll(selector){return selector==='[data-helper-set]'?[]:[original];},classList:{add(...items){items.forEach(item=>classes.add(item));},remove(...items){items.forEach(item=>classes.delete(item));}}};
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?cabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-shake-status'?status:null;},querySelectorAll(){return [];}},window:{matchMedia(){return reduced;},setInterval(fn){shakeTick=fn;},setTimeout(fn,ms){timers.push({fn,ms});}}});
shakeClick();assert.equal(knob.disabled,true);assert(classes.has('is-shaking'));assert.equal(timers.length,9);
shakeClick();assert.equal(timers.length,9);timers[0].fn();assert(classes.has('is-spilling'));
assert(!classes.has('is-door-revealed'));timers[1].fn();assert(classes.has('is-door-revealed'));assert.equal(original.href,'/collector/item/99');timers[2].fn();assert(classes.has('is-helper-arriving'));timers[3].fn();assert(classes.has('is-restocking'));timers[4].fn();assert(classes.has('is-helper-returning'));timers[5].fn();assert(classes.has('is-helper-gesture'));timers[6].fn();assert(classes.has('is-doorman-leaving'));timers[7].fn();assert(classes.has('is-door-closing'));timers[8].fn();assert.equal(classes.size,0);assert.equal(knob.disabled,false);
reduced.matches=true;shakeClick();assert.equal(timers.length,9);assert.equal(classes.size,0);assert.equal(status.textContent,'');
console.log('OK: cabinet Easter egg restores original nodes/links, ignores repeated clicks and respects reduced motion');
reduced.matches=false;
const chosen=new Set(),helpers=[0,1,2].map(index=>({classList:{toggle(_,on){if(on)chosen.add(index);else chosen.delete(index);}}}));
const helperSet={dataset:{},querySelectorAll(){return helpers;}},helperTimers=[];
const helperCabinet={querySelectorAll(selector){return selector==='[data-helper-set]'?[helperSet]:[];},classList:{add(){},remove(){}}};
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?helperCabinet:selector==='.regal-shake-trigger'?knob:null;},querySelectorAll(){return [];}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn){helperTimers.push(fn);}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.deepEqual([...chosen],[0]);helperTimers[8]();shakeClick();assert.deepEqual([...chosen],[1]);helperTimers[17]();
console.log('OK: exactly one helper selected and a different helper on next shake');
const scene=[],cloneStyle={setProperty(name,value){this[name]=value;}},clone={classList:{add(){}},style:cloneStyle};
const stage={replaceChildren(){scene.length=0;},appendChild(node){scene.push(node);}};
const geometricHelpers=helpers.map(helper=>({...helper,cloneNode(){return clone;}}));
const geometricSet={dataset:{},querySelectorAll(){return geometricHelpers;},closest(){return {getBoundingClientRect(){return {left:10,bottom:300};},querySelector(selector){assert.equal(selector,'.regal-shelf-board');return {getBoundingClientRect(){return {top:200};}};}};}};
const geometricCabinet={querySelector(){return stage;},querySelectorAll(selector){return selector==='[data-helper-set]'?[geometricSet]:[];},getBoundingClientRect(){return {left:0,top:0};},classList:{add(){},remove(){}},setAttribute(){}};
const door={getBoundingClientRect(){return {left:100,width:42,bottom:554};}},sceneTimers=[];
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?geometricCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:null;},querySelectorAll(){return [];},createElement(){return {style:{setProperty(name,value){this[name]=value;}}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){sceneTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.equal(scene.length,2);assert.equal(cloneStyle.left,'22px');assert.equal(cloneStyle.top,'98px');
assert.equal(cloneStyle['--door-x'],'54px');assert.equal(cloneStyle['--door-y'],'344px');
assert.equal(cloneStyle['--out-facing'],'-1');assert.equal(cloneStyle['--return-facing'],'1');
assert.deepEqual(sceneTimers.map(timer=>timer.ms),[400,1450,2950,8950,20950,26950,30450,32550,33550]);
sceneTimers.at(-1).fn();assert.equal(scene.length,0);assert.equal(knob.disabled,false);
console.log('OK: cloned scene geometry, shared door/ladder path, phase timing and complete scene cleanup');
// Real inventory links survive sports shots; the empty category spine is excluded.
const sportClasses=new Set(),sportItem={href:'/collector/item/ball-test',style:{setProperty(name,value){this[name]=value;}},classList:{add(name){sportClasses.add(name);},remove(name){sportClasses.delete(name);}},getBoundingClientRect(){return {left:160,top:40,width:20,height:140};}};
clone.dataset={character:'sport-blue'};
const sportHelper={dataset:{character:'sport-blue'},classList:{toggle(){}},cloneNode(){return clone;}};
const sportCompartment={getBoundingClientRect(){return {left:10,bottom:300};},querySelectorAll(selector){assert.equal(selector,'.regal-item');return [sportItem];}};
const sportSet={dataset:{},querySelectorAll(){return [sportHelper];},closest(){return sportCompartment;}};
const sportCabinet={...geometricCabinet,querySelectorAll(selector){return selector==='[data-helper-set]'?[sportSet]:[sportItem];}};
const sportTimers=[];
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?sportCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:null;},querySelectorAll(){return [];},createElement(){return {style:{setProperty(name,value){this[name]=value;}},setAttribute(){}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){sportTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.equal(scene.length,3);assert(sportClasses.has('sport-restock'));
const shot=scene[2];assert.equal(shot.className,'regal-sport-ball');assert.equal(shot.style['--shot-delay'],'300ms');assert.equal(shot.style['--shot-x'],'0.5px');assert.equal(shot.style['--shot-y'],'-79px');
assert.equal(sportItem.href,'/collector/item/ball-test');sportTimers.at(-1).fn();assert.equal(scene.length,0);assert.equal(sportClasses.size,0);assert.equal(sportItem.href,'/collector/item/ball-test');
reduced.matches=true;shakeClick();assert.equal(sportTimers.length,9);assert.equal(scene.length,0);reduced.matches=false;
console.log('OK: sports shot coordinates, native media links, category exclusion, cleanup and reduced motion');
// Duplicate identities across categories are skipped even if that leaves a set empty.
const identities=['sport-blue','sport-red','pirate-captain','pirate-swordsman','detective-blue','detective-red','rapper-cap','rapper-shades'],uniqueChosen=new Set();
const uniqueSets=identities.map((character,index)=>({dataset:{},querySelectorAll(){return [{dataset:{character},classList:{toggle(_,on){if(on)uniqueChosen.add(index);else uniqueChosen.delete(index);},remove(){uniqueChosen.delete(index);}}}];}}));
const uniqueCabinet={querySelectorAll(selector){return selector==='[data-helper-set]'?uniqueSets:[];},classList:{add(){},remove(){}}};
const uniqueTimers=[];
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?uniqueCabinet:selector==='.regal-shake-trigger'?knob:null;},querySelectorAll(){return [];}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn){uniqueTimers.push(fn);}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.deepEqual([...uniqueChosen],[0,2,4,6]);uniqueTimers[8]();shakeClick();assert.deepEqual([...uniqueChosen],[0,2,4,6]);uniqueTimers[17]();
console.log('OK: one character per theme across categories and repeated scenes');
// Shared doorway traffic is staggered, and the guard waits for the last return.
const queueClones=[],queueTimers=[];
const queueSets=Array.from({length:3},(_,index)=>({dataset:{},querySelectorAll(){return [{dataset:{character:'queue-'+index},classList:{toggle(){}},cloneNode(){const c={classList:{add(){}},style:{setProperty(name,value){this[name]=value;}}};queueClones.push(c);return c;}}];},closest(){return {getBoundingClientRect(){return {left:index*200,bottom:300};}};}}));
const queueCabinet={...geometricCabinet,querySelectorAll(selector){return selector==='[data-helper-set]'?queueSets:[];}};
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?queueCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:null;},querySelectorAll(){return [];},createElement(){return {style:{setProperty(name,value){this[name]=value;}}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){queueTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.deepEqual(queueClones.map(c=>c.style['--helper-start']),['0ms','1100ms','2200ms']);
assert.deepEqual(queueClones.map(c=>c.style['--out-facing']),['-1','1','1']);
assert.deepEqual(queueClones.map(c=>c.style['--return-facing']),['1','-1','-1']);
assert.deepEqual(queueTimers.map(t=>t.ms),[400,1450,2950,11150,23150,31350,34850,36950,37950]);
queueTimers.at(-1).fn();assert.equal(scene.length,0);assert.equal(knob.disabled,false);
console.log('OK: doorway queue and guard timing wait for every helper');
// Four security workers finish assembly before helpers; retrieval starts after all return.
const securityClasses=new Set(),securityTimers=[],securityClones=[];
const securityTemplates=Array.from({length:4},(_,index)=>({cloneNode(){const node={dataset:{securityId:'security-'+index},classList:{add(){}},style:{setProperty(name,value){this[name]=value;}},appendChild(){}};securityClones.push(node);return node;}}));
const securitySets=Array.from({length:2},(_,index)=>({dataset:{},querySelectorAll(){return [{dataset:{character:'different-'+index},classList:{toggle(){}},cloneNode(){return {classList:{add(){}},style:{setProperty(name,value){this[name]=value;}}};}}];},closest(){return {getBoundingClientRect(){return {left:10,bottom:300+index*200};}};}}));
const securityCabinet={...geometricCabinet,querySelectorAll(selector){return selector==='[data-helper-set]'?securitySets:[];},classList:{add(...names){names.forEach(n=>securityClasses.add(n));},remove(...names){names.forEach(n=>securityClasses.delete(n));}}};
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?securityCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:selector==='.regal-security-pool'?{querySelectorAll(){return securityTemplates;}}:null;},querySelectorAll(){return [];},createElement(){return {style:{setProperty(name,value){this[name]=value;}}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){securityTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.equal(securityClones.length,4);assert.equal(scene.filter(n=>n.className==='regal-helper-ladder').length,1);
assert.deepEqual(securityClones.map(n=>n.style['--crew-start']),['0ms','1100ms','2200ms','3300ms']);
assert.deepEqual([...securityTimers].map(t=>t.ms).sort((a,b)=>a-b),[400,1450,2200,14250,26650,38650,51050,62650,66150,68250,69250]);
const at=ms=>securityTimers.find(t=>t.ms===ms).fn();
at(2200);assert(securityClasses.has('is-security-building'));at(14250);assert(!securityClasses.has('is-security-building'));assert(securityClasses.has('is-ladders-ready'));at(51050);assert(securityClasses.has('is-security-removing'));assert(!securityClasses.has('is-ladders-ready'));at(62650);assert(!securityClasses.has('is-security-removing'));assert(securityClasses.has('is-helper-gesture'));at(69250);assert.equal(securityClasses.size,0);assert.equal(scene.length,0);assert.equal(knob.disabled,false);
console.log('OK: four unique security workers, shared column ladder, assembly before helpers and retrieval after final return');
// Pirate actions reveal real inventory items without spawning a football.
clone.dataset.character='pirate-captain';sportHelper.dataset.character='pirate-captain';const pirateTimers=[];
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?sportCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:null;},querySelectorAll(){return [];},createElement(){return {style:{setProperty(name,value){this[name]=value;}},setAttribute(){}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){pirateTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.equal(scene[2].className,'regal-pirate-burst');assert.equal(scene[2].textContent,'✦');assert.equal(scene[2].style.left,'170px');assert.equal(scene[2].style.top,'110px');assert.equal(sportItem.href,'/collector/item/ball-test');pirateTimers.at(-1).fn();assert.equal(scene.length,0);assert.equal(sportClasses.size,0);
console.log('OK: pirate inventory reveal, unchanged direct link and complete cleanup');

// The guard uses the category panel's measured position, rather than cabinet centre.
const guardStyle={setProperty(name,value){this[name]=value;}},guardTimers=[],guardCabinet={...geometricCabinet,querySelectorAll(){return [];}};
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?guardCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:selector==='.regal-doorman'?{style:guardStyle}:null;},querySelectorAll(){return [];},createElement(){return {style:{setProperty(){}}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){guardTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.equal(guardStyle['--guard-left'],'122px');assert.equal(guardStyle['--guard-top'],'458px');assert.equal(guardStyle['--guard-door-x'],'-51px');assert.equal(guardStyle['--return-facing'],'-1');guardTimers.at(-1).fn();
console.log('OK: opposite facing directions, guard route follows real category entrance');
// Six occupied compartments need six different themes and four shared column ladders.
const completeClones=[],completeTimers=[],birdStyle={setProperty(name,value){this[name]=value;}},bird={classList:{remove(){},add(){}},style:birdStyle};
const birdId={value:'bird-mask',getAttribute(){return this.value;},setAttribute(_,v){this.value=v;}},birdClip={value:'url(#bird-mask)',getAttribute(){return this.value;},setAttribute(_,v){this.value=v;}};bird.querySelectorAll=selector=>selector==='[id]'?[birdId]:selector==='[clip-path]'?[birdClip]:[];
const completeThemes=['sport-blue','pirate-captain','detective-blue','falconer-ranger','rapper-cap','profession-baker'];
const completeSets=completeThemes.map((character,index)=>({dataset:{},querySelectorAll(){return [{dataset:{character,preferredTheme:character.split('-')[0]},classList:{remove(){},toggle(){}},cloneNode(){const c={dataset:{character},querySelector(){return {cloneNode(){return bird;}};},classList:{add(){}},style:{setProperty(name,value){this[name]=value;}}};completeClones.push(c);return c;}}];},closest(){return {getBoundingClientRect(){return {left:(index%4)*200,bottom:index<4?300:550};},querySelectorAll(){return index===3?[sportItem]:[];}};}}));
const completeCabinet={...geometricCabinet,querySelectorAll(selector){return selector==='[data-helper-set]'?completeSets:[];}};
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?completeCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:null;},querySelectorAll(){return [];},createElement(){return {className:'',style:{setProperty(name,value){this[name]=value;}}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){completeTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();assert.equal(completeClones.length,6);assert.equal(scene.filter(n=>n.className==='regal-helper-ladder').length,4);assert(scene.includes(bird));assert.equal(birdStyle['--bird-delay'],'0ms');assert.equal(birdStyle['--bird-x'],'-576px');
assert(birdId.value.startsWith('scene-1-bird-'));assert.equal(birdClip.value,'url(#'+birdId.value+')');
assert(completeClones.every(clone=>clone.style['--park-x']==='80px'));
assert(parseFloat(completeClones[4].style['--helper-return-start'])-parseFloat(completeClones[0].style['--helper-return-start'])>=6400);
assert(parseFloat(completeClones[5].style['--helper-return-start'])-parseFloat(completeClones[1].style['--helper-return-start'])>=6400);
assert(parseFloat(completeClones[4].style['--helper-return-start'])>parseFloat(completeClones[3].style['--helper-return-start']));
completeTimers.at(-1).fn();assert.equal(scene.length,0);assert.equal(knob.disabled,false);
const birdCss=fs.readFileSync('app/static/collection-shelf.css','utf8');assert(birdCss.includes('95%{opacity:1;transform:translate(0,0) scaleX(-1)}'));assert(birdCss.includes('.regal-flying-bird{display:none!important;animation:none!important}'));
console.log('OK: six distinct themes, four ladders, supplied bird target/return and complete cleanup');
// DOM order must not send the lower helpers down before those above them.
const reorderedCabinet={...completeCabinet,querySelectorAll(selector){return selector==='[data-helper-set]'?[completeSets[4],completeSets[5],...completeSets.slice(0,4)]:[];}};
const reorderedStart=completeClones.length;
vm.runInNewContext(source,{document:{hidden:false,querySelector(selector){return selector==='.collection-regal'?reorderedCabinet:selector==='.regal-shake-trigger'?knob:selector==='.regal-helper-door'?door:null;},querySelectorAll(){return [];},createElement(){return {className:'',style:{setProperty(name,value){this[name]=value;}}};}},window:{matchMedia(){return reduced;},setInterval(){},setTimeout(fn,ms){completeTimers.push({fn,ms});}},Math:{floor:Math.floor,round:Math.round,max:Math.max,min:Math.min,random(){return 0;}}});
shakeClick();const reordered=completeClones.slice(reorderedStart);
assert(parseFloat(reordered[0].style['--helper-return-start'])-parseFloat(reordered[2].style['--helper-return-start'])>=6400);
assert(parseFloat(reordered[1].style['--helper-return-start'])-parseFloat(reordered[3].style['--helper-return-start'])>=6400);
completeTimers.at(-1).fn();assert.equal(scene.length,0);
console.log('OK: upper helpers return first even when lower shelves occur first in DOM');
